# -*- coding: utf-8 -*-
"""Image Captioning with BLIP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PTO84-InVnbuPbI6gGhKjwGKYm93Cot

# Image Captioning with BLIP
This notebook demonstrates how to use the BLIP (Bootstrapping Language-Image Pre-training) model from Salesforce to generate both unconditional and conditional captions for uploaded images.

## 1. Setup and Model Loading
"""

!pip install -q transformers torch torchvision pillow
from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import torch
from google.colab import files
import matplotlib.pyplot as plt

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device:', device)

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model     = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large").to(device)
print("Model loaded ✓")

"""## 2. Image Upload and Captioning"""

def caption_image(img_path):
    img     = Image.open(img_path).convert('RGB')
    inputs1 = processor(img, return_tensors='pt').to(device)
    inputs2 = processor(img, text="a photo of", return_tensors='pt').to(device)

    cap1 = processor.decode(model.generate(**inputs1, max_new_tokens=50, num_beams=5)[0], skip_special_tokens=True)
    cap2 = processor.decode(model.generate(**inputs2, max_new_tokens=50, num_beams=5)[0], skip_special_tokens=True)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    for ax, (title, cap) in zip(axes, [('Unconditional', cap1), ('Conditional', cap2)]):
        ax.imshow(img)
        ax.set_title(f'{title}:\n{cap}', fontsize=11)
        ax.axis('off')
    plt.tight_layout()
    plt.show()
    print(f' Caption 1: {cap1}')
    print(f' Caption 2: {cap2}')

uploaded = files.upload()
caption_image(list(uploaded.keys())[0])

